title: openSUSE-Community
email: webmaster@opensuse-community.org
description: Multimedia codecs, NVidia drivers and more via one click install for the current openSUSE distributions
baseurl: ""
url: "https://www.opensuse-community.org/"
github_username: opensuse-community
github: opensuse-community
repository: opensuse-community/os-com.github.io

# Build settings
markdown: kramdown
exclude: ["README.md"]
plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-compose

collections:
  documentation:
    output: "true"

exclude:
   - .jekyll-cache/
   - bin/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
